### ISSUE TITLE
False restriction after using osu!helper

### ISSUE THREAD

**Issue by RobinMesaMarin** [Tyrrrz/OsuHelper#1]
Hello Tyrrrz,

I tried osu! helper, it worked well I had no problem ... But now, my account is in restricted mode, I hope itsn't a deliberate issue and you'll fix it :)

Sincerly, Oku

**Comment by Tyrrrz** [comment]
Hello Okuuu,

Are you sure that the restriction is caused by using my program? Have you used the default preferences or changed some of the properties to higher values (although making too many queries shouldn't restrict you but rather prevent you from sending more requests).

Anyway, the code for this program is open source and there's nothing malicious in it, as you can check yourself.

**Comment by RobinMesaMarin** [comment]
Thanks for the quick reply !

I'm absolutely not sure my restriction is due to your program, but it's the only thing weird I did today and I never had problem before ... If it's not from your program I have absolutely no idea where did it come from ...

But I have an idea ... A friend told me "osu! helper" is also a name for a cheat tool ... Maybe osu! has dectected a software with this name a blocked me ... It's just an idea ...

edit: As for your question, I'm using the default preferences and haven't changed anything in particular

**Comment by Tyrrrz** [comment]
None of the other users seem to have reported being restricted from using it and my account is also fine.
I haven't thought about it being a name for a cheat. Although it's really stupid if it just restricts people based on the application names they have running in the background.
I'll forward this thread to peppy.

**Comment by RobinMesaMarin** [comment]
It took few hours before I get restricted but if no one else complain your software should not be in question ...

Thanks anyway ! :)

**Comment by Tyrrrz** [comment]
Regardless of the reason, you should message support about your restriction.
If needed, post link to this thread.

**Comment by Tyrrrz** [comment]
@Okuuu what's your osu! username?

**Comment by Ephemeralis** [comment]
I've fixed the issue that could potentially cause this on our end - shouldn't happen again.

**Comment by RobinMesaMarin** [comment]
Well, thanks @Tyrrrz and @Ephemeralis :)
