### ISSUE TITLE
Not opening

### ISSUE THREAD

**Issue by stargame25** [Tyrrrz/OsuHelper#10]
I opening Osu! Helper and it's invisible. I did reinstallation and not working

**Comment by Tyrrrz** [comment]
What OS?

**Comment by stargame25** [comment]
Windows 7

**Comment by stargame25** [comment]
I used it before, but for now it's not working

**Comment by Tyrrrz** [comment]
By "now", do you mean you updated to a newer version? Or else what happened between the two states?

**Comment by stargame25** [comment]
i updated and it's was working about few days and now not working

**Comment by stargame25** [comment]
maybe i just need to delete local files i mean like in %appdata% somewhere?

**Comment by Tyrrrz** [comment]
Yeah try doing that, there should be a folder in %appdata% called "OsuHelper" (or "OsuRepleh", don't remember)

**Comment by stargame25** [comment]
Yes it work

**Comment by stargame25** [comment]
Also ty for support

**Comment by Tyrrrz** [comment]
NP. It was probably something about your settings (as it's the only thing stored in appdata). If it happens again, try to remember what settings you changed before it stopped working, so I can figure out the issue.
