### ISSUE TITLE
What in the world is API key and how do I get one?

### ISSUE THREAD

**Issue by NicoFilippo** [Tyrrrz/OsuHelper#12]
title, i'm just lost...

**Comment by Tyrrrz** [comment]
Hi,
Have you seen the "Generate API key" link in the options screen?
![3](https://user-images.githubusercontent.com/1935960/47749851-a5394880-dc96-11e8-8bbc-f21d28a40357.png)

**Comment by NicoFilippo** [comment]
Ooooh, i thaught that's for developers, because of the url and stuff.

Thanks for the quick reply.

**Comment by Tyrrrz** [comment]
You're welcome
