### ISSUE TITLE
Add Gatari API support

### ISSUE THREAD

**Issue by cptslow-osu** [Tyrrrz/OsuHelper#14]
https://osu.gatari.pw/docs/api

Private servers are left to the devs devices when it comes to recommendations and Gatari's FokaBot recommendation system is particularly awful (regularly suggests maps without Bancho or Gatari FCs to high 3digits), therefore I'm requesting you kindly add that feature to this tool which I love using on Bancho. I'd like to thank you in advance for taking a gander at this even if you decide not to work on it. 

Regards,
Aidan

**Comment by Tyrrrz** [comment]
I'll see what I can do. It would be much easier to implement if Gatari provided some compatibility layer with the official osu api because looking at the link you've sent me their api is quite significantly different.

**Comment by Tyrrrz** [comment]
Closing this issue, as the project has went into maintenance mode and new features are not going to be added.
