### ISSUE TITLE
Keyword filter

### ISSUE THREAD

**Issue by VINXIS** [Tyrrrz/OsuHelper#15]
Hey idunno if ur still working on this but its a really cool tool

i was wondering if there could be a filter option so we could filter words like `Sotarks` and get a list that either doesnt have the maps that pass the filter or has only those maps

**Comment by Tyrrrz** [comment]
Hey @VINXIS, thanks for the suggestion.
I'm still interested in making improvements to this project, although with time constraints it's difficult. I'll do it as soon as I have some spare time. :)

**Comment by Tyrrrz** [comment]
Unfortunately closing this issue, as the project has went into maintenance mode and new features are not going to be added.
