### ISSUE TITLE
Doesn't work on 32bit installation of Windows

### ISSUE THREAD

**Issue by Danial-Syahrum** [Tyrrrz/OsuHelper#16]
I've downloaded .NET but still can't open Osu Helper, Help!

**Comment by Tyrrrz** [comment]
Hi.
By ".NET" do you mean the .NET Core Runtime from here? https://dotnet.microsoft.com/download/dotnet-core/current/runtime

There is also a short guide how to install it here:
https://github.com/Tyrrrz/LightBulb/wiki/How-to-install-.NET-Core-runtime

**Comment by Danial-Syahrum** [comment]
Yes, I already installed it but I still can't open Osu Helper, I installed the 32 bit version because my laptop is old. the previous version of Osu Helper works but it keeps updating to the latest version.

**Comment by Tyrrrz** [comment]
Interesting. Can you also try the x64 version just in case?

If that also doesn't work, you can download the older version and create a file called `Config.dat` with the following content:

```json
{
     "IsAutoUpdateEnabled": false
}
```

If you already have `Config.dat`, just replace this one value.

**Comment by Danial-Syahrum** [comment]
Unfortunately, I can't install x64 version because my laptop is 32bit. However, after I created the config.dat file, it can't auto update itself, and it's working properly now! Thank you so much for helping me!

**Comment by Tyrrrz** [comment]
Just curious, if you have time to test it out, could you download the latest version again to some separate directory and try to launch it from command line using `dotnet OsuHelper.dll` instead of running the `OsuHelper.exe`. It will help me narrow down the problem.

**Comment by Tyrrrz** [comment]
Just curious, if you have time to test it out, could you download the latest version again to some separate directory and try to launch it from command line using `dotnet OsuHelper.dll` instead of running the `OsuHelper.exe`. It will help me narrow down the problem

**Comment by Tyrrrz** [comment]
I fixed this issue in the last commit. You can try using the CI build for now (download from artifacts):

https://github.com/Tyrrrz/OsuHelper/actions/runs/63298763
