### ISSUE TITLE
Error when trying to update

### ISSUE THREAD

**Issue by HippoFalcon** [Tyrrrz/OsuHelper#17]
The application use to work fine, but recently I get a long error and the application closes when I try to update. I have tried un/reinstalling and generating a new API key.
![osuhelper error](https://user-images.githubusercontent.com/22823074/80270984-cd86e500-868a-11ea-8a37-ae756581e89a.PNG)

**Comment by Tyrrrz** [comment]
Can't reproduce this.
Can you give me your userid and what game mode you're using?

**Comment by HippoFalcon** [comment]
My username is HippoFalcon, userID is 15747555, and this is on osu!standard

**Comment by Tyrrrz** [comment]
Seems to work for me (with my API key and your user ID):

![image](https://user-images.githubusercontent.com/1935960/80305490-b862a100-87c5-11ea-89fe-fa022a0d262c.png)

I have no idea why that error is happening. Nothing at the reported line should be causing any errors.

It probably won't help, but you can also try the latest CI build which is a bit newer:

https://github.com/Tyrrrz/OsuHelper/actions/runs/69239447

**Comment by HippoFalcon** [comment]
The latest CI build worked actually. If anything goes awry again I'll let you know. Thanks so much.

**Comment by Tyrrrz** [comment]
Glad it helped
