### ISSUE TITLE
OsuHelper crashes when finding recommendations for top players

### ISSUE THREAD

**Issue by amoongust** [Tyrrrz/OsuHelper#18]
OsuHelper v2.2 crashes when finding recommendations for top 100 players and some players below. I don't know the exact criteria for it crashing.
Also, due to the new ctb pp update OsuHelper v2.2 crashes when looking for ctb recommendations too. For some reason, OsuHelper v1.3.6~ actually does work and shows the updated ctb pp values, but still doesn't work for top players.

**Comment by Tyrrrz** [comment]
Hi.
Can you give me the names of players that caused it to crash (both top players and ctb)?
It has been a really long time since I played myself.

**Comment by amoongust** [comment]
I had the problems listed above around 10~12 hours ago, now everything is working fine. When I was using top 100 ctb player names like secre, - n a g i -, amlink, snowless, the program disappeared before recommendations were given. 
Now, everything is working again. :). The only small issue is that the program is using the old ctb star rating but the PP numbers are accurate. Thanks for the program. I have been using it for a couple of years now.

**Comment by Tyrrrz** [comment]
Great! Probably osu API was having some issues.

> The only small issue is that the program is using the old ctb star rating but the PP numbers are accurate

I guess that's just what osu returns. I've seen there is newer version of the API in the works, maybe that one returns the new CtB star rating.
