### ISSUE TITLE
Api key problem

### ISSUE THREAD

**Issue by rudyon** [Tyrrrz/OsuHelper#19]
When clicking on the "Generate API key." it seems to direct you to https://osu.ppy.sh/p/api/ . Which asks for an application name and a website. Are people supposed to fill these themselves and then put the key that is generated in the application? If this is the case it sounds really fishy. I assume this is stored in an encrypted file? I have not checked the code but this is what I simply assume. If this is the case it is terribly unsafe.

**Comment by Tyrrrz** [comment]
Hi. Yes, that's how it works. That's not up to me.
