### ISSUE TITLE
Restrictions still occurring

### ISSUE THREAD

**Issue by octoberU** [Tyrrrz/OsuHelper#2]
https://osu.ppy.sh/ss/5903951
Literally just happened, downloaded the program an hour ago, as I said in the reddit post I couldnt even open the program due to it crashing on start up.

**Comment by Tyrrrz** [comment]
Can you post your osu! username so Ephemeralis can check?

**Comment by octoberU** [comment]
october
https://osu.ppy.sh/u/5513481

**Comment by octoberU** [comment]
It also happened on stream if you want a past broadcast
https://clips.twitch.tv/octoberosu/HandsomeOstrichYouWHY

**Comment by Tyrrrz** [comment]
@Ephemeralis there seem to be reports of this still happening

**Comment by octoberU** [comment]
Isn't it possible to make a web version of the app? or an in-game bot, maybe pair up with ameo?
This would be 100% fix due to it not being detected in the system

**Comment by Tyrrrz** [comment]
Sorry, I'm not a web dev and I don't really know ameo's dev.

Did you have the app open while playing too?

**Comment by octoberU** [comment]
I couldn't even get it to start since it crashed on start up with "Osu!helper stopped working"
However I'm not sure whether I had osu running in the background while attempting to run it

**Comment by octoberU** [comment]
*It crashed as I hit update, let me correct myself there

**Comment by Tyrrrz** [comment]
I reproduced your crash by entering your name. It crashed because it couldn't acquire any plays with your username, which means you were restricted before using the app, or at the very least - before pressing Update. Some people said it took them an hour to get restricted or they at least could use the app for some time first, so it's very likely that your restriction might be unrelated.

**Comment by octoberU** [comment]
Watch the stream, I also posted the reddit comment before getting restricted(1 hour ago). and I got banned on stream like 20 mins ago.

**Comment by octoberU** [comment]
Also, why would I cheat on a game that I have spent so many hours on and pay supporter for. There are no other reasons for my restrictions, as you can see by the clip above I didn't make an insane pp play or anything in the past 3 days. so there is no way this is cheating related

**Comment by Tyrrrz** [comment]
I didn't say anything like that, I just said that you were already restricted before you pressed "Update". I already tagged @Ephemeralis in this thread, so he will respond when he can. Meanwhile I suggest contacting support.

**Comment by octoberU** [comment]
I mean, I can't really show you that the app crashes since I don't have any other user APIs, but I'm 100% sure I wasn't restricted prior to the updating the app.

**Comment by octoberU** [comment]
I was literally just restricted on stream, where as the comment I left about me being unable to update the app was written an hour before it.

**Comment by octoberU** [comment]
http://puu.sh/qJyEH.png - Me reporting the issue
http://puu.sh/qJyGS.jpg - Exact time of restriction as showed above.
2 Hours inbetween each other

**Comment by Tyrrrz** [comment]
Do you judge when you got restricted by the moment you went offline? One of the users who reported the restriction issue was messaging me in-game saying that his "scores don't submit" and he went offline only about half an hour later.
Anyway, there's not much more I can personally do to help you. In case my app got you restricted, I'm sorry.
I'm pretty sure support should be aware of the issue, so if you message them, they may be able to help you faster.
