### ISSUE TITLE
Linux/MacOS port

### ISSUE THREAD

**Issue by ThePooN** [Tyrrrz/OsuHelper#3]
Any chance for a Linux/MacOS port (using Mono)?
I tried opening the project in MonoDevelop but unfortunately "this project type is not supported by MonoDevelop", and I didn't go any further.

(Note that I couldn't get it to work on Wine, probably because of .NET 4.5.1. Maybe I could get it working if you focus it to .NET 4.0 or 4.5, but the oldest will work the best)

**Comment by Tyrrrz** [comment]
Does MonoDevelop support WPF projects? Never used it, so I'm not sure.
Unfortunately, it uses async/await so I can't really downgrade to .net 4.0, at least not without changing some code.
I've changed the target framework to 4.5, see if it helps in the next release.

**Comment by ThePooN** [comment]
I'm not sure Mono supports WPF projects unfortunately.

Having it working on Wine would be a great start though, especially since osu! still need it. Will tell you when the next release is out!

**Comment by Tyrrrz** [comment]
Oops, referenced wrong issue, disregard that

**Comment by Tyrrrz** [comment]
Please try the new release

**Comment by ThePooN** [comment]
Seems to be working great! However, is it supposed to be using 194Mb of RAM? That's quite big for what your program is IMO.
I don't think Wine should use more RAM, since osu! actually only uses 500Mb... which is very decent!

If you don't intend to support this with Mono, I guess you can close this issue.

**Comment by ThePooN** [comment]
Hm, nevermind. The app is crashing a lot. Sometimes it crashes by resizing, or just by clicking on the tabs... or just randomly. I still managed to got a list of suggestions, though.

**Comment by Tyrrrz** [comment]
I'm afraid I can't help you further. It uses ~40mb on my Windows PC, while osu! uses ~200mb. The fact that it works through Wine is already an accomplishment :)
