### ISSUE TITLE
Material design for the TabControl

### ISSUE THREAD

**Issue by Erinaaaaaaa** [Tyrrrz/OsuHelper#4]
I saw you're using the Material Design in XAML Toolkit, but the tabs aren't skinned.

Using the [Dragablz](https://github.com/ButchersBoy/Dragablz) library (available as a NuGet package) and some more setup that can be found on the linked GitHub page, you can set up your TabControl to be a dragablz:TabablzControl
So it would become Material-styled too

**Comment by Tyrrrz** [comment]
Thank you, will implement that

**Comment by Erinaaaaaaa** [comment]
oh wait, i forgot to link how to setup the material design actually. [here](https://dragablz.net/2015/02/09/how-to-use-the-material-design-theme-with-dragablz-tab-controlgithub/) is how to setup material for the Dragablz controls

**Comment by Tyrrrz** [comment]
Yes, I've found a link myself, but thank you :)

**Comment by Tyrrrz** [comment]
Done
