### ISSUE TITLE
Pack libraries into main executable

### ISSUE THREAD

**Issue by Erinaaaaaaa** [Tyrrrz/OsuHelper#5]
You're releasing the project with many required DLLs next to it. While it's not a wrong solution, packing those DLLs into the executable looks more practical (just like I do with [my own program](https://osu.ppy.sh/forum/t/478865))

To do this, you could use the NuGet package Costura.Fody (no configuration needed). Just install it and it does the job. It embeds the DLLs in the main .exe file and even compress them ;)

**Comment by Tyrrrz** [comment]
I'm aware of that approach, but I'm not planning to implement it for this project in the near future. Maybe later.

**Comment by Erinaaaaaaa** [comment]
I get why you don't pack the libraries into the executable: oppai doesn't get packed so i don't see any more point in packing them
