### ISSUE TITLE
Not parsing UserID from user link, showing an error on update

### ISSUE THREAD

**Issue by octoberU** [Tyrrrz/OsuHelper#8]
http://puu.sh/qLxiW.jpg
All help appreciated.

**Comment by octoberU** [comment]
Just tried getting a new API, didn't seem to solve the issue.

**Comment by Tyrrrz** [comment]
Use your user id, not the user link

**Comment by Erinaaaaaaa** [comment]
@Tyrrrz What about parsing the UID from the link just like with beatmaps?

**Comment by octoberU** [comment]
Thanks a lot, keep up the good work.

**Comment by Tyrrrz** [comment]
@Jeremiidesu will do :)

**Comment by Tyrrrz** [comment]
Fixed
