### ISSUE TITLE
Get the currently playing beatmap and set the BeatmapID to that for quick analysis in calculator

### ISSUE THREAD

**Issue by Tyrrrz** [Tyrrrz/OsuHelper#9]
I see 2 options implementing that, both problematic
1. Get the osu! window title which contains the current song's full title. 
   
   Pros:
   - Easy to implement
   
   Cons:
   - Only works when the user actually plays something, so doesn't work in menu or song select
   - Have to extract the beatmap's data and then search for it somehow, but the API doesn't allow searching by beatmap's name.
2. Use the msn live thingy
   
   Pros:
   - Works anywhere
   - I assume it exposes more information about beatmap, so no search required
   
   Cons:
   - I have no idea how it works
   - The user needs to set a checkbox in the options
   - May become obsolete and get removed at any point because nobody uses msn anymore

**Comment by Piotrekol** [comment]
> msn live thingy

It doesn't expose any more information than you are able to see in osu! window title while playing, so you still would need to do some sort of search to identify a specific map

**Comment by Tyrrrz** [comment]
@Piotrekol not even the beatmap ID?

**Comment by Piotrekol** [comment]
[status] [artist] - [title] [difficulty]
so no.

**Comment by Tyrrrz** [comment]
Ugh, I see.

In your application, did you search through the API somehow or did you scan the user's song folder?

**Comment by Piotrekol** [comment]
I don't like calling online sources for every little thing, so in my application I depend on 2 ways to get map data:
1. get mapID from osu! internal memory and use (2) using only mapid as search criteria(this part of the code isn't public)
2. search database using raw string given from osu!
database I'm searching in is generated using already existing osu!.db in osu! folder

**Comment by Tyrrrz** [comment]
Looking at osu!.db, it seems to also contain the hash strings of the beatmaps.
Do you know what database format is it in?

**Comment by Piotrekol** [comment]
it is documented there(but I'm unsure if it's current schema)
https://osu.ppy.sh/wiki/Db_(file_format)
or you can try poking around [in that file](https://github.com/Piotrekol/StreamCompanion/blob/master/osu!StreamCompanion/Code/Modules/MapDataFinders/OsuDatabaseLoader.cs)
